"""relation user and setting

Revision ID: 791e3ab7e02c
Revises: add650873566
Create Date: 2025-07-22 21:36:33.432251

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "791e3ab7e02c"
down_revision: str | Sequence[str] | None = "add650873566"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settings", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "settings", ["user_id"])
    op.create_foreign_key(None, "settings", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "settings", type_="foreignkey")
    op.drop_constraint(None, "settings", type_="unique")
    op.drop_column("settings", "user_id")
    # ### end Alembic commands ###
